"""Emit src/core/lucide_glyphs.lua from Lucide's info.json.

Reads the JSON at --info, writes a Lua module holding {[name] = codepoint}
for every icon.

Baked at build time rather than fetched at runtime: icon names never change
once assigned, and a second HTTP call to a static file buys nothing but a
second failure mode.

Usage:
  python tools/gen_lucide_glyphs.py --info /path/to/info.json
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "src" / "core" / "lucide_glyphs.lua"

# CSS-style escape: "\\e585" as four characters -> 0xe585.
CSS_ESCAPE = re.compile(r"^\\([0-9a-fA-F]+)$")
# HTML entity: "&#58757;" -> 58757 decimal.
HTML_ENTITY = re.compile(r"^&#(\d+);$")


def decode(meta: dict) -> int | None:
    # Two formats in the wild -- older releases carry both. Try the entity
    # first because it is unambiguous decimal; the CSS escape is next.
    if isinstance(meta.get("unicode"), str):
        m = HTML_ENTITY.match(meta["unicode"])
        if m:
            return int(m.group(1))
        # A raw hex string with no delimiters is possible in older bundlers.
        try:
            return int(meta["unicode"], 16)
        except ValueError:
            pass
    if isinstance(meta.get("encodedCode"), str):
        m = CSS_ESCAPE.match(meta["encodedCode"])
        if m:
            return int(m.group(1), 16)
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--info", required=True,
                    help="Path to Lucide's info.json (from lucide-static or a release)")
    args = ap.parse_args()

    info = json.loads(Path(args.info).read_text(encoding="utf-8"))

    entries: list[tuple[str, int]] = []
    for name, meta in info.items():
        code = decode(meta)
        if code is None:
            print(f"warn: no codepoint for {name}", file=sys.stderr)
            continue
        entries.append((name, code))

    entries.sort()

    lines = [
        "-- Generated by tools/gen_lucide_glyphs.py, do not edit by hand.",
        "-- Regenerate from a Lucide info.json release when the font is updated.",
        "--",
        "-- Lua 5.4 / Luau intersection: this table is loaded by src/core/icons.lua",
        "-- whose resolveIcon runs under the local test harness.",
        "",
        "return {",
    ]
    for name, code in entries:
        lines.append(f'    ["{name}"] = 0x{code:04x},')
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(entries)} icons)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
