"""Emit src/core/lucide_assets.lua from icons.rest's name-to-assetId mapping.

The mapping is scraped once from icons.rest and committed as
assets/icons_rest.json; this tool converts that JSON into a Lua table.

Regeneration is only needed when icons.rest adds new icons (Lucide grows).

Usage:
  python tools/gen_lucide_assets.py
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "assets" / "icons_rest.json"
OUT = REPO / "src" / "core" / "lucide_assets.lua"


def main() -> int:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    entries = sorted(data.items())

    lines = [
        "-- Generated by tools/gen_lucide_assets.py, do not edit by hand.",
        "-- Sourced from icons.rest, a community project that uploads every",
        "-- Lucide icon to Roblox as an image asset. Regenerate when the",
        "-- upstream mapping changes.",
        "--",
        "-- Lua 5.4 / Luau intersection: this table is loaded by",
        "-- src/core/icons.lua whose resolveIcon runs under the local harness.",
        "",
        "return {",
    ]
    for name, asset_id in entries:
        lines.append(f'    ["{name}"] = "{asset_id}",')
    lines.append("}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)} ({len(entries)} icons)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
